import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:quraan/conttrol/cubit.dart';
import 'package:quraan/conttrol/states.dart';
class New extends StatelessWidget {
  int numberSurahs;
  New(this.numberSurahs);
  @override
  Widget build(BuildContext context) {
    return BlocConsumer<Quraan,ShopState>(
      listener: (context,state){},
      builder: (context,state){
        Quraan cubit=Quraan.get(context);
        return Scaffold(
          appBar: AppBar(),
          body: SafeArea(
            minimum: EdgeInsets.all(15),
            child: ListView(
              children: [
                Padding(
                  padding: EdgeInsets.all(5),
                ),
                SizedBox(),
                RichText(
                  text: TextSpan(
                    children: [
                      for(int i =0;i<cubit.autogenerated.data.surahs[numberSurahs].ayahs.length;i++,)...{
                        TextSpan(
                          text:cubit.autogenerated.data.surahs[numberSurahs].ayahs[i].text,
                          style: const TextStyle(color: Colors.black,fontSize: 27),
                        ),
                        WidgetSpan(
                          alignment: PlaceholderAlignment.middle,
                          child: Padding(
                            padding: const EdgeInsets.symmetric(horizontal: 5),
                            child: Stack(
                              alignment: AlignmentDirectional.center,
                              children: [
                                Image.asset(
                                  'image/body.jpg',
                                  width: 39,
                                  height: 25,
                                  fit: BoxFit.cover,
                                ),
                                Text(
                                  //'${i+1}',
                                  ' '+ cubit.autogenerated.data.surahs[numberSurahs].ayahs[i].numberInSurah.toString()+' ',
                                  textScaleFactor: i.toString().length<2?1:.8,
                                  style: TextStyle(color: Colors.white,
                                    fontWeight: FontWeight.bold,
                                  ),
                                ),
                              ],
                            ),
                          ),
                        ),
                      }
                    ],
                  ),
                )
              ],
            ),
          ),
        );
      },
    );
  }
}
